name: ShopMefy-DB
version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: shopmefy
      POSTGRES_PASSWORD: shopmefy
      POSTGRES_DB: shopmefy
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopmefy"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: